return {
  -- "saghen/blink.cmp",
  -- opts = {
  --   keymap = {
  --     ["<Tab>"] = {
  --       function(cmp)
  --         if cmp.snippet_active() then
  --           return cmp.accept()
  --         else
  --           return cmp.select_and_accept()
  --         end
  --       end,
  --       "select_next",
  --       "fallback",
  --     },
  --     ["<S-Tab>"] = {
  --       "select_prev",
  --       "fallback",
  --     },
  --   },
  -- },
}
